version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/practice/
    overwrite: yes
hooks:
  BeforeInstall:
    - location: scripts/container_stop.sh
  AfterInstall:
    - location: scripts/image_build.sh
  ApplicationStart:
    - location: scripts/run.sh
